char *regetable =
"#\n"
"# robot control 12\n"
"#\n"
"@@ Start			<x float> <y float> <z float> <rx float> <ry float> <rz float> <v float> <a float> <al float> <a2 float> <a3 float> <a4 float> <a5 float> <a6 float> <a7 float> <rad float : 0> \n"
"@@ MoveJ			<x float> <y float> <z float> <rx float> <ry float> <rz float> <v float> <a float> <al float> <a2 float> <a3 float> <a4 float> <a5 float> <a6 float> <a7 float> <rad float : 0> \n"
"@@ MoveL			<x float> <y float> <z float> <rx float> <ry float> <rz float> <v float> <a float> <al float> <a2 float> <a3 float> <a4 float> <a5 float> <a6 float> <a7 float> <rad float : 0> \n"
"@@ MoveC_1			<x float> <y float> <z float> <rx float> <ry float> <rz float> <v float> <a float> <al float> <a2 float> <a3 float> <a4 float> <a5 float> <a6 float> <a7 float> <rad float : 0> \n"
"@@ MoveC_2			<x float> <y float> <z float> <rx float> <ry float> <rz float> <v float> <a float> <al float> <a2 float> <a3 float> <a4 float> <a5 float> <a6 float> <a7 float> <rad float : 0> \n"
"@@ MovePsi			<x float> <y float> <z float> <rx float> <ry float> <rz float> <v float> <a float> <al float> <a2 float> <a3 float> <a4 float> <a5 float> <a6 float> <a7 float> <rad float : 0> \n"

"@@ Sleep			<time int> \n"
"@@ sleep			<time int> \n"
"@@ gripper			<num int> \n"
"@@ io_out			<portnum int> <val int> \n"
"@@ io_in			<port int>							# return val int \n"
"@@ tool_out		<portnum int> <val int> \n"
"@@ tool_in			<port int>							# return val int \n"
//"@@ run_prog		<name string>						# return val int \n"

"# \n"
"# new robot move 7 \n"
"# \n"
"@@ start			<axis array> <v float> <a float>  <rad float : 0> \n"
"@@ movej			<axis array> <v float> <a float>  <rad float : 0> \n"
"@@ movej_pose		<p pose> <v float> <a float> \n"
"@@ movel			<p pose> <v float> <a float> <rad float : 0> <psi float : 999> \n"
"@@ movec			<p1 pose> <p2 pose> <v float> <a float> <rad float : 0> <psi float : 999> \n"
"@@ movepsi			<axis array> <v float> <a float> <rad float : 0> \n"
"@@ set_tcp			<x float> <y float> <z float> <rx float> <ry float> <rz float> \n"
"@@ clean_tcp \n"
"@@ tcp_move		<x float> <y float> <z float> <v float> \n"
"@@ get_flange_pos	<p pose> \n"
"@@ get_joint_pos	<axis array> \n"
"@@ replay          <num int> <speed int : 50> \n"

"# \n"
"# socket_func 3 \n"
"# \n"
"@@ socket_open		<ip string> <port int>				# return True or False \n"
"@@ socket_get_var	<name string> \n"
"@@ socket_close \n"
"@@ socket_send_string <str string>						# retrun True or False \n"
"@@ socket_read_string <str string> <len int>			# retrun True or False \n"

"# \n"
"# camera 1 \n"
"# \n"
"@@ capture			<ip string> <actionnum int> <arr array> <recvsize int> <timeout int : 5000>		# return int \n"
"@@ calpos			<x float> <y float> <res array>	<num int : 1>	# return int\n"
"# \n"
"# developer func 5 \n"
"# \n"
"@@ calib_start						# return val int \n"
"@@ calib_finish						# return val int \n"
"@@ robot_move_finished		<a int> \n"
"@@ robot_move_write		<a int> \n"
"@@ robot_move						# return val int \n"
"@@ moveCalib		<a int> \n"
"@@ calibAdjustPose \n"
"@@ biaoding					<x float> <y float> <z float> <rx float> <ry float> <rz float> <v float> <a float> <al float> <a2 float> <a3 float> <a4 float> <a5 float> <a6 float> <a7 float> <rad float : 0>";
